sudo: false

jobs:
  include:
    # These are the latest Go versions.
    - os: linux
      dist: xenial
      language: go
      go: 1.13.x
      branches:
        only:
          - master
      script:
        - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - os: osx
      language: go
      go: 1.13.x
      branches:
        only:
          - master
      script:
        - echo "Increase the maximum number of open file descriptors on macOS"
        - NOFILE=20480
        - sudo sysctl -w kern.maxfiles=$NOFILE
        - sudo sysctl -w kern.maxfilesperproc=$NOFILE
        - sudo launchctl limit maxfiles $NOFILE $NOFILE
        - sudo launchctl limit maxfiles
        - ulimit -S -n $NOFILE
        - ulimit -n
        - unset -f cd # workaround for https://github.com/travis-ci/travis-ci/issues/8703
        - go test -v ./...
