sudo: false

jobs:
  include:
    - stage: lint
      os: linux
      dist: xenial
      language: go
      go: 1.13.x
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod
      install:
        - export GO111MODULE="off"
        - ./scripts/install_go_lint.sh
      script:
        - ./scripts/go_lint.sh
    
    - stage: unit test
      os: linux
      dist: xenial
      language: go
      go: 1.13.x
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod
      script:
        - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - stage: unit test
      os: osx
      language: go
      go: 1.13.x
      cache:
        directories:
          - $HOME/Library/Caches/go-build
          - $HOME/gopath/pkg/mod
      script:
        - unset -f cd # workaround for https://github.com/travis-ci/travis-ci/issues/8703
        - go test -v ./...
